WebApiIdentity2/Models/AccountMvcViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApiIdentity2.Models
{
    public class AccountMvcViewModel
    {
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

WebApiIdentity2/Controllers/AccountMvcController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OAuth;
using WebApiIdentity2.Models;
using WebApiIdentity2.Providers;
using WebApiIdentity2.Results;

namespace WebApiIdentity2.Controllers
{
    public class AccountMvcController : Controller
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        
        // GET: /Account/Register
        [HttpGet]
        [System.Web.Http.AllowAnonymous]
        public ActionResult RegisterUser()
        {
            return View();
        }

        // POST api/Account/Register
        [System.Web.Http.AllowAnonymous]
        //[ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> RegisterUser(RegisterViewModel model)
        {
            //if (!System.Web.Http.ModelBinding.ModelState.IsValid)
            //{
            //    return BadRequest(System.Web.Http.ModelBinding.ModelState);
            //}

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser() { UserName = model.Email, Email = model.Email };

                var result = await UserManager.CreateAsync(user, model.Password);
                if (!result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                //return View();
            }

            //if (!result.Succeeded)
            //{
            //    return RedirectToRoute("Default", new { controller = "Home", action = "Index" });
            //}

            //return Ok();
            return View(model);

        }
    }
}

WebApiIdentity2/Views/AccountMvc/Login.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

WebApiIdentity2/Views/AccountMvc/RegisterUser.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model WebApiIdentity2.Models.RegisterViewModel
@{
    ViewBag.Title = "RegisterUser";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("RegisterUser", "AccountMvc", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="RegisterUser" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApiIdentity2/Views/AccountMvc/UserList.cshtml
@{
    ViewBag.Title = "UserList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UserList</h2>